#!/usr/bin/env php
<?php
require_once __DIR__ . '/vendor/autoload.php';


use App\console\Migrate;
use App\console\Migration;
use App\console\Model;
use Symfony\Component\Console\Application;

$app = new Application();
$app->add(new Migrate());
$app->add(new Migration());
$app->add(new Model());
$app->run();